### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by jh0ker** [philhk/betterdiscord-plugin-template#1]
Let me start off by saying Thank You for publishing this, it's been a great help for starting out with making a plugin!

I started working on my [first plugin](https://github.com/jh0ker/better-discord-transcribe-voice-notes) yesterday based on this template, and I'd like to provide a license for it. Without a license on your code, I also don't feel comfortable publishing my plugin properly, if I ever decide to do so.

Therefore, I would greatly appreciate if you took the time to choose a license and added it to this repository. I recommend https://choosealicense.com/ if you are unsure about which license to pick.

**Comment by philhk** [comment]
Hey,

Thanks for the heads up and glad the template has been useful! You're right about the license I'll add a suitable one really quick.

Appreciate the suggestion!

**Comment by jh0ker** [comment]
Awesome! Thank you again!
